export const ADD_TO_CART='ADD_TO_CART';
export const ADD_TO_CART_ASYNC='ADD_TO_CART_ASYNC';
export const INCREASE_QUANTITY='INCREASE_QUANTITY';
export const DECREASE_QUANTITY='DECREASE_QUANTITY';
export const ADD_TO_FAVORITES='ADD_TO_FAVORITES';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
